FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

ENV TORCH_CUDA_ARCH_LIST="8.0 8.6+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install MMCV, MMDetection and MMSegmentation
RUN pip install mmcv-full==1.3.15 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
RUN pip install mmdet==2.17.0
RUN pip install mmsegmentation==0.18.0

# Install MMDetection3D
RUN conda clean --all
RUN git clone https://github.com/Bovey0809/merge_monster_3d.git /mmdetection3d && cd /mmdetection3d && git reset --hard 640eab2f7cfb2865250aff2b048c577c7934ed50

WORKDIR /mmdetection3d
ENV FORCE_CUDA="1"

RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e .

# rebuild mmcv
RUN pip uninstall -y mmcv-full 
RUN git clone https://github.com/open-mmlab/mmcv.git && cd mmcv && MMCV_WITH_OPS=1 pip install -e .

# reinstall pycocotools
RUN pip uninstall -y pycocotools
RUN pip install pycocotools==2.0.1